//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Pose p_default_Pose;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonLeftHand;
        
        private static SteamVR_Action_Skeleton p_default_SkeletonRightHand;
        
        private static SteamVR_Action_Boolean p_default_HeadsetOnHead;
        
        private static SteamVR_Action_Boolean p_default_TriggerClick;
        
        private static SteamVR_Action_Boolean p_default_PadClick;
        
        private static SteamVR_Action_Boolean p_default_Menu;
        
        private static SteamVR_Action_Boolean p_default_Grip;
        
        private static SteamVR_Action_Boolean p_default_PadTouch;
        
        private static SteamVR_Action_Boolean p_default_TriggerTouch;
        
        private static SteamVR_Action_Vector2 p_default_PadTouchValue;
        
        private static SteamVR_Action_Single p_default_TriggerValue;
        
        private static SteamVR_Action_Boolean p_default_DPadNorth;
        
        private static SteamVR_Action_Boolean p_default_DPadSouth;
        
        private static SteamVR_Action_Boolean p_default_DPadWest;
        
        private static SteamVR_Action_Boolean p_default_DPadEast;
        
        private static SteamVR_Action_Boolean p_default_DPadCenter;
        
        private static SteamVR_Action_Vibration p_default_Haptic;
        
        public static SteamVR_Action_Pose default_Pose
        {
            get
            {
                return SteamVR_Actions.p_default_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonLeftHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Skeleton default_SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.p_default_SkeletonRightHand.GetCopy<SteamVR_Action_Skeleton>();
            }
        }
        
        public static SteamVR_Action_Boolean default_HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.p_default_HeadsetOnHead.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TriggerClick
        {
            get
            {
                return SteamVR_Actions.p_default_TriggerClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_PadClick
        {
            get
            {
                return SteamVR_Actions.p_default_PadClick.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Menu
        {
            get
            {
                return SteamVR_Actions.p_default_Menu.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_Grip
        {
            get
            {
                return SteamVR_Actions.p_default_Grip.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_PadTouch
        {
            get
            {
                return SteamVR_Actions.p_default_PadTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_TriggerTouch
        {
            get
            {
                return SteamVR_Actions.p_default_TriggerTouch.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vector2 default_PadTouchValue
        {
            get
            {
                return SteamVR_Actions.p_default_PadTouchValue.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single default_TriggerValue
        {
            get
            {
                return SteamVR_Actions.p_default_TriggerValue.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Boolean default_DPadNorth
        {
            get
            {
                return SteamVR_Actions.p_default_DPadNorth.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_DPadSouth
        {
            get
            {
                return SteamVR_Actions.p_default_DPadSouth.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_DPadWest
        {
            get
            {
                return SteamVR_Actions.p_default_DPadWest.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_DPadEast
        {
            get
            {
                return SteamVR_Actions.p_default_DPadEast.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean default_DPadCenter
        {
            get
            {
                return SteamVR_Actions.p_default_DPadCenter.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration default_Haptic
        {
            get
            {
                return SteamVR_Actions.p_default_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TriggerClick,
                    SteamVR_Actions.default_PadClick,
                    SteamVR_Actions.default_Menu,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_PadTouch,
                    SteamVR_Actions.default_TriggerTouch,
                    SteamVR_Actions.default_PadTouchValue,
                    SteamVR_Actions.default_TriggerValue,
                    SteamVR_Actions.default_DPadNorth,
                    SteamVR_Actions.default_DPadSouth,
                    SteamVR_Actions.default_DPadWest,
                    SteamVR_Actions.default_DPadEast,
                    SteamVR_Actions.default_DPadCenter,
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_Pose,
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand,
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TriggerClick,
                    SteamVR_Actions.default_PadClick,
                    SteamVR_Actions.default_Menu,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_PadTouch,
                    SteamVR_Actions.default_TriggerTouch,
                    SteamVR_Actions.default_PadTouchValue,
                    SteamVR_Actions.default_TriggerValue,
                    SteamVR_Actions.default_DPadNorth,
                    SteamVR_Actions.default_DPadSouth,
                    SteamVR_Actions.default_DPadWest,
                    SteamVR_Actions.default_DPadEast,
                    SteamVR_Actions.default_DPadCenter};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.default_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.default_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TriggerClick,
                    SteamVR_Actions.default_PadClick,
                    SteamVR_Actions.default_Menu,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_PadTouch,
                    SteamVR_Actions.default_TriggerTouch,
                    SteamVR_Actions.default_DPadNorth,
                    SteamVR_Actions.default_DPadSouth,
                    SteamVR_Actions.default_DPadWest,
                    SteamVR_Actions.default_DPadEast,
                    SteamVR_Actions.default_DPadCenter};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.default_TriggerValue};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.default_PadTouchValue};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[] {
                    SteamVR_Actions.default_SkeletonLeftHand,
                    SteamVR_Actions.default_SkeletonRightHand};
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.default_HeadsetOnHead,
                    SteamVR_Actions.default_TriggerClick,
                    SteamVR_Actions.default_PadClick,
                    SteamVR_Actions.default_Menu,
                    SteamVR_Actions.default_Grip,
                    SteamVR_Actions.default_PadTouch,
                    SteamVR_Actions.default_TriggerTouch,
                    SteamVR_Actions.default_PadTouchValue,
                    SteamVR_Actions.default_TriggerValue,
                    SteamVR_Actions.default_DPadNorth,
                    SteamVR_Actions.default_DPadSouth,
                    SteamVR_Actions.default_DPadWest,
                    SteamVR_Actions.default_DPadEast,
                    SteamVR_Actions.default_DPadCenter};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_default_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/default/in/Pose")));
            SteamVR_Actions.p_default_SkeletonLeftHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonLeftHand")));
            SteamVR_Actions.p_default_SkeletonRightHand = ((SteamVR_Action_Skeleton)(SteamVR_Action.Create<SteamVR_Action_Skeleton>("/actions/default/in/SkeletonRightHand")));
            SteamVR_Actions.p_default_HeadsetOnHead = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/HeadsetOnHead")));
            SteamVR_Actions.p_default_TriggerClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TriggerClick")));
            SteamVR_Actions.p_default_PadClick = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/PadClick")));
            SteamVR_Actions.p_default_Menu = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Menu")));
            SteamVR_Actions.p_default_Grip = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/Grip")));
            SteamVR_Actions.p_default_PadTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/PadTouch")));
            SteamVR_Actions.p_default_TriggerTouch = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/TriggerTouch")));
            SteamVR_Actions.p_default_PadTouchValue = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/default/in/PadTouchValue")));
            SteamVR_Actions.p_default_TriggerValue = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/default/in/TriggerValue")));
            SteamVR_Actions.p_default_DPadNorth = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/DPadNorth")));
            SteamVR_Actions.p_default_DPadSouth = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/DPadSouth")));
            SteamVR_Actions.p_default_DPadWest = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/DPadWest")));
            SteamVR_Actions.p_default_DPadEast = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/DPadEast")));
            SteamVR_Actions.p_default_DPadCenter = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/default/in/DPadCenter")));
            SteamVR_Actions.p_default_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/default/out/Haptic")));
        }
    }
}
