//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.default_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadClick
        {
            get
            {
                return SteamVR_Actions.default_PadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.default_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.default_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadTouch
        {
            get
            {
                return SteamVR_Actions.default_PadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.default_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PadTouchValue
        {
            get
            {
                return SteamVR_Actions.default_PadTouchValue;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerValue
        {
            get
            {
                return SteamVR_Actions.default_TriggerValue;
            }
        }
        
        public virtual SteamVR_Action_Boolean DPadNorth
        {
            get
            {
                return SteamVR_Actions.default_DPadNorth;
            }
        }
        
        public virtual SteamVR_Action_Boolean DPadSouth
        {
            get
            {
                return SteamVR_Actions.default_DPadSouth;
            }
        }
        
        public virtual SteamVR_Action_Boolean DPadWest
        {
            get
            {
                return SteamVR_Actions.default_DPadWest;
            }
        }
        
        public virtual SteamVR_Action_Boolean DPadEast
        {
            get
            {
                return SteamVR_Actions.default_DPadEast;
            }
        }
        
        public virtual SteamVR_Action_Boolean DPadCenter
        {
            get
            {
                return SteamVR_Actions.default_DPadCenter;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
