//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_TestControlsSet : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.testControlsSet_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadClick
        {
            get
            {
                return SteamVR_Actions.testControlsSet_PadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.testControlsSet_Menu;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.testControlsSet_Grip;
            }
        }
        
        public virtual SteamVR_Action_Boolean PadTouch
        {
            get
            {
                return SteamVR_Actions.testControlsSet_PadTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.testControlsSet_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Vector2 PadTouchValue
        {
            get
            {
                return SteamVR_Actions.testControlsSet_PadTouchValue;
            }
        }
        
        public virtual SteamVR_Action_Single TriggerValue
        {
            get
            {
                return SteamVR_Actions.testControlsSet_TriggerValue;
            }
        }
    }
}
